before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/kubectl-colorize-applied
    binary: kubectl-colorize_applied
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    files:
      - LICENSE
      - README.md
    wrap_in_directory: false
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
