apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: colorize-applied
spec:
  version: {{ .TagName }}
  homepage: https://github.com/cappyzawa/kubectl-colorize-applied
  shortDescription: "Colorize results of apply/dry-run"
  description: |
    This plugin colorizes the results of apply/dry-run.
    Each line containing the following strings is colored:
    "pruned", "configured", "created", and "unchanged".
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/cappyzawa/kubectl-colorize-applied/releases/download/{{ .TagName }}/kubectl-colorize-applied-darwin-amd64.tar.gz" .TagName }}
    bin: kubectl-colorize_applied
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/cappyzawa/kubectl-colorize-applied/releases/download/{{ .TagName }}/kubectl-colorize-applied-darwin-arm64.tar.gz" .TagName }}
    bin: kubectl-colorize_applied
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/cappyzawa/kubectl-colorize-applied/releases/download/{{ .TagName }}/kubectl-colorize-applied-linux-amd64.tar.gz" .TagName }}
    bin: kubectl-colorize_applied
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/cappyzawa/kubectl-colorize-applied/releases/download/{{ .TagName }}/kubectl-colorize-applied-linux-arm64.tar.gz" .TagName }}
    bin: kubectl-colorize_applied
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/cappyzawa/kubectl-colorize-applied/releases/download/{{ .TagName }}/kubectl-colorize-applied-windows-amd64.tar.gz" .TagName }}
    bin: kubectl-colorize_applied.exe
