name: CI

on:
  push:
    branches:
    - main
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: 1.21.x
    - run: "go vet -v ./..."
    - run: "go test -v ./..."
  status-check:
    runs-on: ubuntu-latest
    needs:
    - test
    permissions: {}
    if: failure()
    steps:
    - run: exit 1
  enable-auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write # For enable automerge
      pull-requests: write # For enable automerge
    if: |
      github.event.pull_request.user.login == 'renovate[bot]' && contains(github.event.pull_request.body, ' **Automerge**: Enabled.')
    steps:
    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v2.1.0
      with:
        app_id: ${{secrets.GH_APP_ID}}
        private_key: ${{secrets.GH_APP_PRIVATE_KEY}}
    - run: gh -R "$GITHUB_REPOSITORY" pr merge --squash --auto --delete-branch "$PR_NUMBER"
      env:
        GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}
        PR_NUMBER: ${{github.event.pull_request.number}}
